nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'https://127.0.0.1:8000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
