security:
    # Configuration pour le hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs - Détermine où les utilisateurs sont chargés
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Pare-feux de sécurité
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pare-feu principal pour les API sécurisées
        main:
            lazy: true
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\ApiTokenAuthenticator
            json_login:
                check_path: /api/login

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\ApiTokenAuthenticator

        # Pare-feu pour la connexion API
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

    # Contrôles d'accès
    access_control:
        # Zones d'accès pour les Administrateurs, Employés et Vétérinaires
        - { path: ^/manage-users, roles: ROLE_ADMIN }
        - { path: ^/manage-services, roles: ROLE_EMPLOYE }
        - { path: ^/manage-habitats, roles: ROLE_VETERINAIRE }

        # Accès public pour l'inscription et la connexion
        - { path: ^/api/registration, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/commentaire, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }


when@test:
    security:
        password_hashers:
