name: app

type: php:8.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv

disk: 512

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            expires: 1h

mounts:
    "/var": { source: local, source_path: var }

relationships:
    database: "mysql:mysql"

variables:
    env:
        DATABASE_USER: "root"
        DATABASE_PASSWORD: "UvuZ54hBFAgAgV"
        DATABASE_HOST: "database.internal"
        DATABASE_NAME: "zoo_arcadia"
        DATABASE_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:3306/${DATABASE_NAME}?serverVersion=8.0.32&charset=utf8mb4"

hooks:
    build: |
        set -x -e
        curl -fs https://get.symfony.com/cloud/configurator | bash
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e
        symfony-deploy
