name: app

type: php:8.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv

disk: 512

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            expires: 1h

mounts:
    "/var": { source: local, source_path: var }

relationships:
    database: "mysql:mysql"

variables:
    env:
        DATABASE_URL: "mysql://root:UvuZ5!hBFAgAgV@database.internal:3306/zoo_arcadia?serverVersion=8.0.32&charset=utf8mb4"

hooks:
    build: |
        set -x -e
        curl -fs https://get.symfony.com/cloud/configurator | bash
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e
        symfony-deploy
