# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

employee_home:
    path: /employee
    controller: App\Controller\EmployeeController::index

admin_home:
    path: /admin
    controller: App\Controller\AdminController::index

api_users:
    path: /api/users
    controller: App\Controller\UserController::getUsers
    methods: GET

app.swagger_ui:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui
    methods: GET
