# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

employee_home:
    path: /employee
    controller: App\Controller\EmployeeController::index

admin_home:
    path: /admin
    controller: App\Controller\AdminController::index

api_users:
    path: /api/users
    controller: App\Controller\UserController::getUsers
    methods: GET

api_doc:
    path: /api/doc
    controller: App\Controller\ApiDocController::index
