# Ce fichier est le point d'entrée pour configurer vos propres services.
# Les fichiers dans le sous-répertoire packages/ configurent vos dépendances.

# Mettez ici les paramètres qui ne nécessitent pas de changement sur chaque machine où l'application est déployée
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mongodb_uri: 'mongodb://localhost:27017'
    mongodb_database_name: 'zooarcadia'

services:
    App\Service\MongoDBService:
        autowire: false
        arguments:
            $mongoUri: '%env(MONGODB_URI)%'
            $databaseName: 'zooarcadia'


    # Configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés aux événements, etc.

    # Rendre les classes dans src/ disponibles pour être utilisées en tant que services
    # Cela crée un service par classe dont l'identifiant est le nom complet de la classe
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ajoutez plus de définitions de service lorsque la configuration explicite est nécessaire
    # Veuillez noter que les dernières définitions remplacent toujours les précédentes
